sudo: true
dist: trusty
language: python
matrix:
  include:
    - python: "3.5"
before_install:
  - "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-full latexmk poppler-utils lmodern texlive-xetex"
install:
  - git clone https://github.com/lsst/lsst-texmf.git
script:
  - export TEXMFHOME=./lsst-texmf/texmf
  - make
